# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.LabOneProject: DEBUG


app:
    customers-service:
      host: localhost
      port: 7001
    sneakers-service:
      host: localhost
      port: 7002
    inventory-service:
      host: localhost
      port: 7003
    purchases-service:
      host: localhost
      port: 7004

---

  # for docker

  spring:
    config:
      activate:
        on-profile: docker

  server.port: 8080

  #spring.datasource.hikari.initializationFailTimeout: 60000


  app:
    customers-service:
      host: customers-service
      port: 8080
    sneakers-service:
      host: sneakers-service
      port: 8080
    inventory-service:
      host: inventory-service
      port: 8080
    purchases-service:
      host: purchases-service
      port: 8080